import * as fs from 'fs';
import * as path from 'path';

export class CoverageParserService {
  /**
   * Attempts to parse JSON summary coverage output to find line coverage percentage.
   * Expects a coverage/coverage-summary.json file generated by Jest/Istanbul.
   */
  public getCoveragePercentage(workspaceRoot: string): string {
    const summaryPath = path.join(workspaceRoot, 'coverage', 'coverage-summary.json');
    
    if (fs.existsSync(summaryPath)) {
      try {
        const data = fs.readFileSync(summaryPath, 'utf8');
        const summary = JSON.parse(data);
        
        // Grab global line coverage
        if (summary.total && summary.total.lines) {
          const pct = summary.total.lines.pct;
          return `${pct}%`;
        }
      } catch (err) {
        console.warn('Failed to parse coverage-summary.json', err);
      }
    }
    
    return '0%'; // Fallback
  }
}
