/**
 * Plan State Service: Persists execution plan state between PLAN and CODE phases.
 * Stores plan, agent outputs, and pending/completed step lists.
 * Supports timestamped backups of previous plans.
 */

import * as fs from 'fs';
import * as path from 'path';

/** Represents a single step in the execution plan */
export interface PlanStep {
    step: number;
    agentId: string;
    agentName: string;
    task: string;
    reason: string;
}

/** The full plan generated by the orchestrator */
export interface ExecutionPlan {
    summary: string;
    steps: PlanStep[];
    includeCodeGeneration: boolean;
}

/** Persisted plan state — saved to disk between PLAN / CODE phases */
export interface PersistedPlanState {
    plan: ExecutionPlan;
    agentOutputs: Record<string, string>;
    completedSteps: string[];
    pendingSteps: string[];
    createdAt: number;
    updatedAt: number;
    userRequest: string;
    conversationId?: string;
}

/** Agents that belong to the CODE phase (deferred during PLAN) */
export const CODING_PHASE_AGENTS = new Set([
    'developer',
    'codereview',
    'qa',
    'techwriter',
    'testGenerator',
]);

/**
 * Service for managing plan state persistence between PLAN and CODE phases
 */
export class PlanStateService {
    private planStateDir: string;
    private planStatePath: string;
    private backupDir: string;

    constructor(private workspaceRoot: string) {
        this.planStateDir = path.join(workspaceRoot, '.verno', 'plan-state');
        this.planStatePath = path.join(this.planStateDir, 'plan.json');
        this.backupDir = path.join(this.planStateDir, 'history');
        this.ensureDirectoryExists();
    }

    /**
     * Save plan state to disk (backs up existing state first)
     */
    savePlanState(state: PersistedPlanState): void {
        // Backup existing plan before overwriting
        this.backupPlanState();

        state.updatedAt = Date.now();
        fs.writeFileSync(this.planStatePath, JSON.stringify(state, null, 2), 'utf-8');
    }

    /**
     * Load plan state from disk
     */
    loadPlanState(): PersistedPlanState | null {
        if (!fs.existsSync(this.planStatePath)) {
            return null;
        }
        try {
            const data = fs.readFileSync(this.planStatePath, 'utf-8');
            return JSON.parse(data) as PersistedPlanState;
        } catch {
            return null;
        }
    }

    /**
     * Check if there are pending coding-phase steps
     */
    hasPendingCodingSteps(): boolean {
        const state = this.loadPlanState();
        if (!state) { return false; }
        return state.pendingSteps.some(id => CODING_PHASE_AGENTS.has(id));
    }

    /**
     * Get all pending steps (coding-phase agents)
     */
    getPendingSteps(): PlanStep[] {
        const state = this.loadPlanState();
        if (!state) { return []; }
        return state.plan.steps.filter(s => state.pendingSteps.includes(s.agentId));
    }

    /**
     * Get completed agent outputs
     */
    getAgentOutputs(): Record<string, string> {
        const state = this.loadPlanState();
        if (!state) { return {}; }
        return state.agentOutputs;
    }

    /**
     * Mark a step as complete and store its output
     */
    markStepComplete(agentId: string, output: string): void {
        const state = this.loadPlanState();
        if (!state) { return; }

        state.agentOutputs[agentId] = output;
        state.completedSteps = [...new Set([...state.completedSteps, agentId])];
        state.pendingSteps = state.pendingSteps.filter(id => id !== agentId);
        state.updatedAt = Date.now();

        fs.writeFileSync(this.planStatePath, JSON.stringify(state, null, 2), 'utf-8');
    }

    /**
     * Create an initial plan state from a generated plan
     */
    createFromPlan(
        plan: ExecutionPlan,
        userRequest: string,
        conversationId?: string
    ): PersistedPlanState {
        const allAgentIds = plan.steps.map(s => s.agentId);
        const state: PersistedPlanState = {
            plan,
            agentOutputs: {},
            completedSteps: [],
            pendingSteps: allAgentIds,
            createdAt: Date.now(),
            updatedAt: Date.now(),
            userRequest,
            conversationId,
        };
        return state;
    }

    /**
     * Check if a plan state exists on disk
     */
    hasPlanState(): boolean {
        return fs.existsSync(this.planStatePath);
    }

    /**
     * Clear the current plan state
     */
    clearPlanState(): void {
        this.backupPlanState();
        if (fs.existsSync(this.planStatePath)) {
            fs.unlinkSync(this.planStatePath);
        }
    }

    /**
     * Backup the current plan state with a timestamp
     */
    backupPlanState(): void {
        if (!fs.existsSync(this.planStatePath)) {
            return;
        }

        if (!fs.existsSync(this.backupDir)) {
            fs.mkdirSync(this.backupDir, { recursive: true });
        }

        try {
            const data = fs.readFileSync(this.planStatePath, 'utf-8');
            const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
            const backupPath = path.join(this.backupDir, `plan-${timestamp}.json`);
            fs.writeFileSync(backupPath, data, 'utf-8');
        } catch {
            // Silently ignore backup errors
        }
    }

    /**
     * Get list of backup plans (most recent first)
     */
    getBackupPlans(): Array<{ path: string; timestamp: string }> {
        if (!fs.existsSync(this.backupDir)) {
            return [];
        }
        return fs.readdirSync(this.backupDir)
            .filter(f => f.endsWith('.json'))
            .sort()
            .reverse()
            .map(f => ({
                path: path.join(this.backupDir, f),
                timestamp: f.replace('plan-', '').replace('.json', ''),
            }));
    }

    /**
     * Get a human-readable label describing the current pipeline state.
     * Used by WorkspaceIntelligence to inject SDLC phase into the system prompt.
     */
    getCurrentPhaseLabel(): string | null {
        const state = this.loadPlanState();
        if (!state) { return null; }
        const pending = state.pendingSteps;
        const completed = state.completedSteps;
        if (pending.length === 0) { return 'Pipeline complete'; }
        const nextAgent = pending[0];
        return `${nextAgent} pending (${completed.length}/${state.plan.steps.length} steps done)`;
    }

    /**
     * Ensure plan state directory exists
     */
    private ensureDirectoryExists(): void {
        if (!fs.existsSync(this.planStateDir)) {
            fs.mkdirSync(this.planStateDir, { recursive: true });
        }
    }
}
